#!/bin/bash

# Script to generate all of the automatic input for the main web quiz manual.
# That is, update the lists supported languages and themes and generate all of
# the images used by webquiz.tex

# TODO: rewrite in python to make cross-platform and merge with makeimages

cd "$(dirname $0)/.."
WebQuizDir="$PWD"
WebQuizExamplesDir="$WebQuizDir/doc/examples"
PREFIX=""

function message() {
  if [ "$quiet" = false ]; then
     echo -e "${PREFIX}$@"
  fi
}
function make_languages() {
  message "Generating list of webquiz supported languages"
  cd $WebQuizDir/latex
  LANG=$(ls -1 webquiz-*.lang | xargs | sed 's@webquiz-@@g' | gsed -e 's@\([a-z]*\).lang@\u\1,@g' | sed 's@, \([A-Za-z]*\),$@,, \1@')
  cd $WebQuizDir/doc
  LANGS="webquiz.languages"
  /bin/rm -f $LANGS
  echo "% List of languages currently supported by WebQuiz" > $LANGS
  echo "% Generated using 'makedoc --languages' on $(date '+%Y-%m-%d')" >> $LANGS
  echo "\newcommand\WebQuizLanguages{$LANG}" >> $LANGS
}

function check_examples() {
  message "Checking for unused images from the examples directory"
  cd $WebQuizDir/doc
  /bin/rm -f makedoc-{examples,images,manual}
  echo "Example tex files" > makedoc-examples
  ls -1 examples/*.tex | sed 's@.tex@@' | sed 's@examples.@@' | sort -u >> makedoc-examples
  echo "Included in manual" > makedoc-manual
  ag ScreenShot webquiz.tex|sed 's@.*}{\([^}]*\)}$@\1@'|ag -v Shot|sort -u >> makedoc-manual
  echo "Available images" > makedoc-images
  examples/makeimages --list | sort >> makedoc-images
  gvim -d makedoc-manual makedoc-images makedoc-examples 
}

function make_themes () {
  message "Generating list of webquiz supported css themes"

  if [[ "$fast" == false ]]; then
    message "Rebuilding all themes from scss files"
    /bin/rm -f $WebQuizExamplesDir/theme-*.* $WebQuizDir/css/*.css
  fi

  # next generate code to include screenshots for each theme in the appendix
  cd $WebQuizDir/css
  for theme in webquiz-*.scss ; do
      sass --style compressed $theme ${theme/scss/css}
      name=${theme/webquiz-/}
      name=${name/.scss/}
      if [ ! -e "$WebQuizExamplesDir/theme-$name.tex" ]; then
        # create theme-<theme>.tex if it does not already exist
        sed "s@default@$name@g" $WebQuizExamplesDir/theme.tex > "$WebQuizExamplesDir/theme-$name.tex"
      fi
  done

  if [[ "$makeall" = false ]]; then
    message "Generating theme screenshots for inclusion in manual"
    $WebQuizExamplesDir/makeimages theme
  fi

  message "Generating list of themes for the manual"
  THEME="$WebQuizDir/doc/webquiz.themes"
  /bin/rm -f $THEME
  echo "% List of themes supported by WebQuiz -- generated $(date '+%Y-%m-%d')" > $THEME
  # first generate a list of themes for the documentclass options section
  cd $WebQuizDir/css
  THEMES=$(ls -1 webquiz-*.scss | xargs | sed 's@webquiz-@@g' | sed 's@.scss@,@g' | sed 's@, \([a-z]*\),$@,, \1@')
  echo "\newcommand\WebQuizThemes{$THEMES}" >> $THEME
}

function make_examples() {
  message "Generating webquiz example images"
  cd $WebQuizExamplesDir
  if [[ "$quiet" == true ]]; then
      q="-q"
  else
      q=""
  fi
  /bin/rm -f *-thumb.png *-clipped.png
  if [[ "$fast" == false ]]; then
    ./makeimages -f $q
  else
    ./makeimages $q
  fi
}

function make_settings() {
  message "Generating webquiz settings file"
  cd $WebQuizDir/doc
  /bin/rm -f webquiz.settings
  webquiz --settings >> webquiz.settings
}

function make_usage() {
  message "Generating webquiz usage file"
  cd $WebQuizDir/doc
  /bin/rm -f webquiz.usage
  webquiz --shorthelp >> webquiz.usage
}

function make_online_manual() {
  message "Making pdf for online manual"
  cd $WebQuizDir/doc
  latex webquiz-online-manual && dvipdf webquiz-online-manual
}

function make_all() {
  makeall=true # so that themes are not built twice
  message "Making pdf for manual"
  PREFEX=" - "
  make_languages
  make_settings
  make_themes
  make_usage
  make_examples
  if  [[ "$fast" = false ]] ; then
      make_online_manual
      pdflatex --interaction=batchmode webquiz
      pdflatex --interaction=batchmode webquiz
  fi
  pdflatex --interaction=batchmode webquiz
}

function usage() {
  message "Make --[fast|quiet] --[check-examples|examples|languages|manual|online|themes|]"
}

makeall=false
fast=false
quiet=false # TODO
command=""  # what we need to execute
if [ $# -eq 0 ]; then
  make_all
else
  while [ $# -gt 0 ]
  do
     case $1 in
       -a|--all)
         make_all
         shift ;;
       -c|--check-examples)
         check_examples
         shift ;;
       -e|--examples)
         make_examples
         shift ;;
       -f|--fast)
         fast=true
         shift ;;
       -l|--languages)
         make_languages
         shift ;;
       -o|--online-manual)
         make_online_manual
         shift ;;
       -q|--quiet)
         quiet=true
         shift ;;
       -s|--settings)
         make_settings
         shift ;;
       -t|--theme)
         make_themes
         shift ;;
       -u|--usage)
         make_usage
         shift ;;
       *)
         usage && exit
         shift ;;
     esac
   done
fi
